data:
  dataset: cifar10
  root: ./data/cifar10
  downsample: true
  
  train_split: train
  val_split: test

  batch_size: 64
  num_workers: 8

model:
  resnet:
    arch: resnet18

  branch_enc:
    embd_dim: 256
    out_dim: 128
    n_heads: 4
    n_layers: 5
    attn_pdrop: 0.1
    proj_pdrop: 0.1
    path_pdrop: 0.1
    eos: false
    embd_type: 0
    pe_type: 0

  content_enc:
    out_dim: 128
    arch: resnet8_cifar

  branch_vae:
    hid_dim: 32
    n_layers: 3
    latent_dim: 2

opt:
  epochs: 20
  warmup_epochs: 5
  warmup: [branch_enc, content_enc]

  branch_enc:
    optim_type: adamw
    lr: 1.e-3
    weight_decay: 0.05
    sched_type: cosine

  content_enc:
    optim_type: adamw
    lr: 1.e-3
    weight_decay: 0.05
    sched_type: cosine

  branch_vae: null

  clip_grad_norm: 1.0

train:
  n_branches: 64
  k: 1
  min_n_positives: 64
  temperature: 10

  delta_rs: 0.5
  rank_weight: 1.0
  sort_weight: 1.0
  bce_weight: 0.0

eval:
  n_branches: 128
  max_macs: 1
  batch_size: 128